Controllers/FilmsController.cs
using ITExpertTEST.Data;
using ITExpertTEST.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ITExpertTEST.Controllers
{
    public class FilmsController : Controller
    {
        private readonly AppDBContext _context;

        public FilmsController(AppDBContext context)
        {
            _context = context;
        }

        public IActionResult Index(string categoryFilter = null)
        {
            try
            {
                IQueryable<Film> filmsQuery = _context.Films
                .Include(f => f.FilmCategories)
                .ThenInclude(fc => fc.Category);

                if (!string.IsNullOrEmpty(categoryFilter))
                {
                    int categoryId = int.Parse(categoryFilter);
                    filmsQuery = filmsQuery.Where(f => f.FilmCategories.Any(fc => fc.CategoryId == categoryId));
                }

                var films = filmsQuery.ToList();

                var categories = _context.Categories.ToList();

                ViewData["Categories"] = categories;
                ViewData["SelectedCategory"] = categoryFilter;

                return View(films);
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { error = "An error occurred while updating the film." });
            }
        }

        [HttpPost]
        public ActionResult AddFilm(string filmName, string filmDirector, DateTime releaseDate)
        {
            try
            {
                var newFilm = new Film
                {
                    FilmName = filmName,
                    FilmDirector = filmDirector,
                    Release = releaseDate
                };

                _context.Films.Add(newFilm);
                _context.SaveChanges();

                return Json(new { success = true });
            }
            catch (DbUpdateException ex)
            {
                return StatusCode(500, new { error = "An error occurred while updating the film." });
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            try
            {
                var film = await _context.Films
                .Include(f => f.FilmCategories)
                    .ThenInclude(fc => fc.Category)
                .FirstOrDefaultAsync(f => f.FilmId == id);

                if (film == null)
                    return NotFound();

                var allCategories = _context.Categories.ToList();
                ViewData["AllCategories"] = allCategories;

                return View(film);
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { error = "An error occurred while updating the film." });
            }
        }


        [HttpPost]
        public IActionResult UpdateFilmCategories(int filmId, int[] categoryIds)
        {
            try
            {
                var film = _context.Films
                .Include(f => f.FilmCategories)
                .FirstOrDefault(f => f.FilmId == filmId);

                if (film == null)
                {
                    return NotFound();
                }

                film.FilmCategories.Clear();

                foreach (var categoryId in categoryIds)
                {
                    film.FilmCategories.Add(new FilmCategory { FilmId = filmId, CategoryId = categoryId });
                }

                _context.SaveChanges();

                return Json(new { success = true });
            }
            catch (DbUpdateException ex)
            {
                return StatusCode(500, new { error = "An error occurred while updating the film." });
            }
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFilm(int filmId, string filmName, string filmDirector, DateTime releaseDate)
        {
            var film = await _context.Films.FindAsync(filmId);

            if (film == null)
            {
                return NotFound();
            }

            try
            {
                film.FilmName = filmName;
                film.FilmDirector = filmDirector;
                film.Release = releaseDate;

                _context.Films.Update(film);
                await _context.SaveChangesAsync();

                return Json(new { success = true });
            }
            catch (DbUpdateException ex)
            {
                return StatusCode(500, new { error = "An error occurred while updating the film." });
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteFilm(int filmId)
        {
            var film = await _context.Films.FindAsync(filmId);

            if (film == null)
                return NotFound();

            try
            {
                _context.Films.Remove(film);
                await _context.SaveChangesAsync();

                return Json(new { success = true });
            }
            catch (DbUpdateException ex)
            {
                return StatusCode(500, new { error = "An error occurred while deleting the film." });
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ITExpertTEST</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ITExpertTEST.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchpanes/2.4.1/css/searchPanes.dataTables.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Films" asp-action="Index">ITExpertTEST</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Films" asp-action="Index">All Films</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">All Categories</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ITExpertTEST
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/searchpanes/2.4.1/js/dataTables.searchPanes.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script src="~/js/FilmService.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>